# Generated by Django 2.2.3 on 2019-09-24 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20190825_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Files',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
