# Generated by Django 2.2.3 on 2019-09-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_article_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Files',
        ),
    ]
